name: Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      P6_DFZ_SRC_P6M7G8_DIR: ".."
      TERM: "xterm-256color"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set git identity
        run: |-
          git config user.name "Auto-bump"
          git config user.email "github-actions@github.com"
      - name: Bump and Release
        run:  bin/p6ctl release
      - name: Upload artifact
        uses: actions/upload-artifact@v2.1.1
        with:
          name: dist
          path: .
    container:
      image: jsii/superchain
